{
 "title": "RHHI-V Lab",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "host_set", "label": "Host Set", "query": "label_values(node_load1,job)" },
   {
    "name": "hosts",
    "label": "Hosts",
    "query": "label_values(node_load1{job=~\"$host_set\"},instance)"
   },
   {
    "name": "netdev",
    "label": "Network Interface",
    "query": "label_values(node_network_transmit_bytes_total{instance=~\"$hosts\"},device)"
   },
   {
    "name": "blockdev",
    "label": "Block Device",
    "query": "label_values(node_disk_written_bytes_total{instance=~\"$hosts\"},device)"
   }
  ]
 },
 "panels": [
  {
   "title": "System CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode=\"system\",job=~\"$host_set\",instance=~\"$hosts\"}[30s]) * 100) by (instance,mode)",
     "legendFormat": "{{instance}} - CPU - {{mode}}"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode=\"user\",job=~\"$host_set\",instance=~\"$hosts\"}[30s]) * 100) by (instance,mode)",
     "legendFormat": "{{instance}} - CPU - {{mode}}"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode=\"iowait\",job=~\"$host_set\",instance=~\"$hosts\"}[30s]) * 100) by (instance,mode)",
     "legendFormat": "{{instance}} - CPU - {{mode}}"
    }
   ]
  },
  {
   "title": "System Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active_bytes{job=~\"$host_set\"} / node_memory_MemTotal_bytes{job=~\"$host_set\"}",
     "legendFormat": "{{instance}} - Active %"
    },
    {
     "expr": "node_memory_Cached_bytes{job=~\"$host_set\"} / node_memory_MemTotal_bytes{job=~\"$host_set\"}",
     "legendFormat": "{{instance}} - Cached %"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=~\"$host_set\"}",
     "legendFormat": "{{instance}} - Load - 1m"
    },
    {
     "expr": "node_load5{job=~\"$host_set\"}",
     "legendFormat": "{{instance}} - Load - 5m"
    },
    {
     "expr": "node_load15{job=~\"$host_set\"}",
     "legendFormat": "{{instance}} - Load - 15m"
    }
   ]
  },
  {
   "title": "VMStat",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_vmstat_pgpgin{job=~\"$host_set\"}[30s])",
     "legendFormat": "{{instance}} - Page In Rate"
    },
    {
     "expr": "rate(node_vmstat_pgpgout{job=~\"$host_set\"}[30s])",
     "legendFormat": "{{instance}} - Page Out Rate"
    },
    {
     "expr": "rate(node_vmstat_pgfault{job=~\"$host_set\"}[30s])",
     "legendFormat": "{{instance}} - Fault Rate"
    },
    {
     "expr": "rate(node_vmstat_pgmajfault{job=~\"$host_set\"}[30s])",
     "legendFormat": "{{instance}} - Major Fault Rate"
    }
   ]
  },
  {
   "title": "Network Bandwidth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device=~\"$netdev\",job=~\"$host_set\"}[30s]) * 8) by (instance,device)",
     "legendFormat": "{{instance}} - {{device}} - TX"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device=~\"$netdev\",job=~\"$host_set\"}[30s]) * 8)by (instance,device)",
     "legendFormat": "{{instance}} - {{device}} - RX"
    }
   ]
  },
  {
   "title": "Network Drops & Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_drop_total{device=~\"$netdev\",job=~\"$host_set\"}[30s])) by (instance,device)",
     "legendFormat": "{{instance}} - {{device}} - TX Drop Rate"
    },
    {
     "expr": "sum(rate(node_network_receive_drop_total{device=~\"$netdev\",job=~\"$host_set\"}[30s])) by (instance,device)",
     "legendFormat": "{{instance}} - {{device}} - RX Drop Rate"
    },
    {
     "expr": "sum(rate(node_network_transmit_errs_total{device=~\"$netdev\",job=~\"$host_set\"}[30s])) by (instance,device)",
     "legendFormat": "{{instance}} - {{device}} - TX Err Rate"
    },
    {
     "expr": "sum(rate(node_network_receive_errs_total{device=~\"$netdev\",job=~\"$host_set\"}[30s])) by (instance,device)",
     "legendFormat": "{{instance}} - {{device}} - RX Err Rate"
    }
   ]
  },
  {
   "title": "Drive Total IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{device=~\"$blockdev\",job=~\"$host_set\"}[30s]) + irate(node_disk_writes_completed_total{device=~\"$blockdev\",job=~\"$host_set\"}[30s])",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "Drive Total Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_written_bytes_total{device=~\"$blockdev\",job=~\"$host_set\"}[30s])) by (instance,device) + sum(rate(node_disk_read_bytes_total{device=~\"$blockdev\",job=~\"$host_set\"}[30s])) by (instance,device)",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "Drive Write IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_writes_completed_total{device=~\"$blockdev\",job=~\"$host_set\"}[30s])",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "Drive Write Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_written_bytes_total{device=~\"$blockdev\",job=~\"$host_set\"}[30s])) by (instance,device)",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "Drive Read IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{device=~\"$blockdev\",job=~\"$host_set\"}[30s])",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "Drive Read Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{device=~\"$blockdev\",job=~\"$host_set\"}[30s])) by (instance,device)",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "Drive Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=~\"$blockdev\",job=~\"$host_set\"}[30s])",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  }
 ]
}